import type { Metadata } from 'next'
import '@/app/globals.css'


export const metadata: Metadata = {
  title: 'Sanity Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <section>{children}</section>
      </body>
    </html>
  )
}
