import type { Metadata } from 'next'
import '@/app/globals.css'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { client } from '@/sanity/sanity-utils'
import { groq } from 'next-sanity'
import { TestFilter } from '@/components/test-filter'
import { filterToLower } from '@/components/filter-to-lower'
import { siteConfig } from '@/config/site'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const allProjects = await client.fetch(
    groq`*[_type=="project"]{
      _id,
      _createdAt,
      name,
      images,
      url,
      content,
      type,
      roles,
      role,
      collaborators,
      tags,
      color,
      year,
      "slug": slug.current,
  }`
  )
  filterToLower(allProjects)
  return (
    <html lang="en">
      <body className='bg-black'>
        <SiteHeader />
        <section>
          <TestFilter projects={allProjects}/>
          <>{children}</>
          <SiteFooter />
        </section>
      </body>
    </html>
  )
}
