import type { Metadata } from 'next'
import '@/app/globals.css'
import { SiteFooter } from '@/components/site-footer'
import { client } from '@/sanity/sanity-utils'
import { groq } from 'next-sanity'
import { TestFilter } from '@/components/test-filter'
import { filterToLower } from '@/components/filter-to-lower'
import localFont from 'next/font/local'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const flatspot = localFont({ 
  src: [
    {
      path: '../public/fonts/FlatspotNuovoTest-Bold.woff2',
      weight: '700'
    }
  ],
  variable: "--font-flatspot"
})

const poppins = localFont({ 
  src:'../public/fonts/Poppins-Black.woff',
  variable: "--font-poppins"
})


console.log(poppins)

export default async function RootLayout({
  children,
}: {
    children: React.ReactNode
  }) {


  const info = await client.fetch(
    groq`*[_type=="info"]{
        bio,
    }`
  )
  const allProjects = await client.fetch(
    groq`*[_type=="project"]{
      _id,
      _createdAt,
      name,
      images,
      url,
      content,
      type,
      roles,
      role,
      collaborators,
      tags,
      color,
      year,
      "slug": slug.current,
    }`
  )

  filterToLower(allProjects)
  return (
    <html lang="en">
      <body className={`${poppins.variable} poppins bg-white`}>
        <section>
          <TestFilter projects={allProjects}/>
          <>{children}</>
          <SiteFooter info={info} />
        </section>
      </body>
    </html>
  )
}
